### ISSUE TITLE
设置步态并开始仿真后机器人直接摔倒了

### ISSUE THREAD

**Issue by yzyyyyy2048** [pocketxjl/humanoid-control#1]
您好！非常感谢您的开源工作！
我在运行仿真时，设置完步态后按下空格键启动反正，机器人并没有走起来，而是直接摔倒了，请问是什么原因呢？另外，我看您的演示视频中还有一个终端窗口用来读取键盘输入，请问这个需要自己设置吗？谢谢！

**Comment by pocketxjl** [comment]
您好，你需要检查一下读取键盘输入的终端端口有没有跑起来，控制器需要持续接收cmd_vel才能跑起来。至于为什么没有跑起来，你可以通过rosrun mujoco_sim teleop.py来测试，很可能你没有安装pynput包，装一下就好了
