### ISSUE TITLE
代码运行后，list选择trot，报错了

### ISSUE THREAD

**Issue by 1508189250** [pocketxjl/humanoid-control#11]
roslaunch humanoid_controllers load_cheat_controller.launch
启动这个launch文件报错

[CppAdInterface] Compiling Shared Library: /tmp/ocs2/r_foot_heel_position/cppad_generated/r_foot_heel_position_libcppadcg_tmp78348649.so
[CppAdInterface] Renaming /tmp/ocs2/r_foot_heel_position/cppad_generated/r_foot_heel_position_libcppadcg_tmp78348649.so to /tmp/ocs2/r_foot_heel_position/cppad_generated/r_foot_heel_position_lib.so
[CppAdInterface] Compiling Shared Library: /tmp/ocs2/r_foot_heel_velocity/cppad_generated/r_foot_heel_velocity_libcppadcg_tmp11948649.so
[CppAdInterface] Renaming /tmp/ocs2/r_foot_heel_velocity/cppad_generated/r_foot_heel_velocity_libcppadcg_tmp11948649.so to /tmp/ocs2/r_foot_heel_velocity/cppad_generated/r_foot_heel_velocity_lib.so
[CppAdInterface] Compiling Shared Library: /tmp/ocs2/r_foot_heel_orientation/cppad_generated/r_foot_heel_orientation_libcppadcg_tmp56048649.so
[CppAdInterface] Renaming /tmp/ocs2/r_foot_heel_orientation/cppad_generated/r_foot_heel_orientation_libcppadcg_tmp56048649.so to /tmp/ocs2/r_foot_heel_orientation/cppad_generated/r_foot_heel_orientation_lib.so
WARNING: Failed to set threads priority (one possible reason could be that the user and the group permissions are not set properly.)
WARNING: Failed to set threads priority (one possible reason could be that the user and the group permissions are not set properly.)
WARNING: Failed to set threads priority (one possible reason could be that the user and the group permissions are not set properly.)
WARNING: Failed to set threads priority (one possible reason could be that the user and the group permissions are not set properly.)
[ INFO] [1724380800.602795197]: Waiting for the initial policy ...
[ INFO] [1724380800.613858410]: Initial policy has been received.
ERROR:  Maximum number of working set recalculations performed
ERROR: WeightWBC Not Solved!!!
ERROR:  Maximum number of working set recalculations performed
ERROR: WeightWBC Not Solved!!!
ERROR:  Maximum number of working set recalculations performed
ERROR: WeightWBC Not Solved!!!
ERROR:  Maximum number of working set recalculations performed
ERROR: WeightWBC Not Solved!!!
ERROR:  Maximum number of working set recalculations performed
ERROR: WeightWBC Not Solved!!!
ERROR:  Maximum number of working set recalculations performed

机器人静止不动，控制窗口，按空格，或者其他键也没反应

修改int nWsr = 20;这个代码，把它设置成非常大的一个数int nWsr = 200，就不会报上面的错，但机器人还是静止不动
ctrl+c后报错

ERROR:  Projected Hessian matrix not positive definite
->ERROR:  Removing from active set failed
  ->ERROR:  Unable to perform homotopy step
    ->ERROR:  Removing from active set failed
      ->ERROR:  Initialisation failed! QP could not be solved!
ERROR: WeightWBC Not Solved!!!
ERROR:  Projected Hessian matrix not positive definite
->ERROR:  Removing from active set failed
  ->ERROR:  Unable to perform homotopy step
    ->ERROR:  Removing from active set failed
      ->ERROR:  Initialisation failed! QP could not be solved!
ERROR: WeightWBC Not Solved!!!
^C[normal_controller-4] killing on exit
[humanoid_target-3] killing on exit
########################################################################
########################################################################
###   Average : 0.445099[ms].[SqpSolver] Log written to '/tmp/ocs2/sqp_log/log_Fri_Aug_23_11:55:58_2024.txt'
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete

roslaunch humanoid_dummy legged_robot_sqp.launch
这一个rviz的仿真是正常的

**Comment by pocketxjl** [comment]
控制键盘输入的pynput装了吗？
按空格以后机器人能站住吗？

**Comment by 1508189250** [comment]
> 控制键盘输入的pynput装了吗？ 按空格以后机器人能站住吗？

装了，机器人启动是静止不动的，按了空格键也是静止不动
