### ISSUE TITLE
ERROR:  Maximum number of working set recalculations performed ERROR: WeightWBC Not Solved!!!

### ISSUE THREAD

**Issue by kavinwkp** [pocketxjl/humanoid-control#2]
您好，我运行`legged_robot_sqp.launch`没问题，但是运行前2个launch文件会出现上述问题，您知道是什么原因吗，会不会是mujoco版本问题

**Comment by pocketxjl** [comment]
你好，这只是一个警告，WBC有时候会出现解不出来的情况，这时候会保留上一个时刻的解，如果机器人能行走就可以忽略它。

**Comment by kavinwkp** [comment]
好的，另外，我运行前2个mujoco环境里面机器人一启动就会摔倒，您知道是什么原因吗

**Comment by pocketxjl** [comment]
拉一下最新的代码，编译。
另外，检查一下teleop.py有没有正确运行。

**Comment by pocketxjl** [comment]
代码只有stance和trot两个步态，不知道你所说的第三个步态是什么意思。另外stance的时候腿开始摆动后倒地的问题，怀疑是运行频率跟不上。ctrl+c终止程序后应该会打印出程序运行频率，检查MPC是否在平均10ms以内，wbc是否在平均2ms以内，并检查编译优化选项。

控制器完全启动后，默认的状态是stance，最新的代码中，此时按空格开启仿真应该是能站住的。

**Comment by Zhenyuan-Fu** [comment]
您好，我也遇到相似的问题，stance正常运行。但切换trot时会走几步后倒下。这是和求解频率相关吗。以下是运行频率：########################################################################
### MPC Benchmarking
###   Maximum : 28.3691[ms].
###   Average : 15.8759[ms].
########################################################################
### WBC Benchmarking
###   Maximum : 4.4088[ms].
###   Average : 0.887534[ms].

**Comment by pocketxjl** [comment]
MPC的计算速度有点慢，平均要控制在10ms以内，要不然稳定性会比较差。你可以在运行仿真的时候关掉其它无关的程序节约一下CPU的性能，或者调一下MPC的参数，比如并行线程数，或者调低time horizon让他运行快一些。

**Comment by vanceeasleaf** [comment]
输入trot后毫无反应，连续报下面的错有人遇到过吗

ERROR: WeightWBC Not Solved!!!
ERROR:  Projected Hessian matrix not positive definite
->ERROR:  Removing from active set failed
  ->ERROR:  Unable to perform homotopy step
    ->ERROR:  Removing from active set failed
      ->ERROR:  Initialisation failed! QP could not be solved!
ERROR: WeightWBC Not Solved!!!
ERROR:  Projected Hessian matrix not positive definite
->ERROR:  Removing from active set failed
  ->ERROR:  Unable to perform homotopy step
    ->ERROR:  Removing from active set failed
      ->ERROR:  Initialisation failed! QP could not be solved!
ERROR: WeightWBC Not Solved!!!
ERROR:  Projected Hessian matrix not positive definite
->ERROR:  Removing from active set failed
  ->ERROR:  Unable to perform homotopy step
    ->ERROR:  Removing from active set failed
      ->ERROR:  Initialisation failed! QP could not be solved!
ERROR: WeightWBC Not Solved!!!

**Comment by pocketxjl** [comment]
仿真窗口里面按下空格启动了吗

**Comment by vanceeasleaf** [comment]
按下了的，相关视频都看过了，感觉是ubuntu22下面的什么适配问题
