### ISSUE TITLE
用rqt_multiplot打开zero_velocity.xml以及friction_cone.xml文件时，图表无变化

### ISSUE THREAD

**Issue by zzzzyyyjjj** [pocketxjl/humanoid-control#3]
作者您好！非常感谢您的开源工作！我在运行multiplot.launch时，可以成功弹出两个窗口，其中performance_indices相关图表可以正常显示，而zeroVelocity和FOOT_frictionCone的图表则没有变化。
![image](https://github.com/pocketxjl/humanoid-control/assets/118258722/4383ec7b-11af-42ed-90cd-63e81f4e9af4)
![image](https://github.com/pocketxjl/humanoid-control/assets/118258722/5a4be9b9-f230-4775-a09f-47bfe0e16ce6)
想知道原因，谢谢！QAQ

**Comment by pocketxjl** [comment]
我没有写multiplot相关代码，现在Multiplot相关代码应该仍然是OCS2原本的代码。如果要使用multiplot需要修改代码。

**Comment by zzzzyyyjjj** [comment]
谢谢！另外还想问一个问题，humanoid-control-main/mujoco_sim/script/draw_torque.py需要如何才能作图呢？终端提示“请提供一个有效的整数参数作为索引。”不知道漏了哪一步 :)

**Comment by pocketxjl** [comment]
你需要在终端中输入一个数字，代表腿部第几个关节，比如输入一个3,然后按回车，它就会画出第三个关节即膝关节的力矩变化曲线，具体可查看该文件的python代码

**Comment by pocketxjl** [comment]
从髋关节到踝关节的六个关节分别定义为1到6

**Comment by zzzzyyyjjj** [comment]
好的！谢谢！
