### ISSUE TITLE
读取仿真反馈数据

### ISSUE THREAD

**Issue by rcone11** [pocketxjl/humanoid-control#7]
已经成功运行demo仿真，但是如何获取机器人的反馈数据？我有看到humanoid_sim.py文件并且运行后出现demo窗口可以按照步骤进行正常的行走，但是如何能够获取机器人的反馈信息呢？需要进行什么操作呢？希望大佬可以给一点意见。

**Comment by pocketxjl** [comment]
可以在humanoid_sim.py里面额外发布一些话题来获取数据，或者直接记录ROS里面现有话题
